### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'tag')

### ISSUE THREAD

**Issue by dmgnr** [AkaruiDevelopment/panel#5]
It occurs while trying to view a guild, it throw error and do nothing else

Here's the full error

```error
Unhandled Rejection/Catch                                                                                                                    16:28:40
TypeError: Cannot read properties of undefined (reading 'tag')                                                                               16:28:40
    at /home/superdin/Desktop/NTHS/node_modules/@akarui/aoi.panel/src/framework/guilds.js:61:177
    at Layer.handle [as handle_request] (/home/superdin/Desktop/NTHS/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/superdin/Desktop/NTHS/node_modules/express/lib/router/route.js:144:13)
    at isLoggedIn (/home/superdin/Desktop/NTHS/node_modules/@akarui/aoi.panel/src/frameworkmain.js:21:14)
    at Layer.handle [as handle_request] (/home/superdin/Desktop/NTHS/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/superdin/Desktop/NTHS/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/superdin/Desktop/NTHS/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/superdin/Desktop/NTHS/node_modules/express/lib/router/layer.js:95:5)
    at /home/superdin/Desktop/NTHS/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/superdin/Desktop/NTHS/node_modules/express/lib/router/index.js:346:12) Promise {
  <rejected> TypeError: Cannot read properties of undefined (reading 'tag')
      at /home/superdin/Desktop/NTHS/node_modules/@akarui/aoi.panel/src/framework/guilds.js:61:177
      at Layer.handle [as handle_request] (/home/superdin/Desktop/NTHS/node_modules/express/lib/router/layer.js:95:5)
      at next (/home/superdin/Desktop/NTHS/node_modules/express/lib/router/route.js:144:13)
      at isLoggedIn (/home/superdin/Desktop/NTHS/node_modules/@akarui/aoi.panel/src/frameworkmain.js:21:14)
      at Layer.handle [as handle_request] (/home/superdin/Desktop/NTHS/node_modules/express/lib/router/layer.js:95:5)
      at next (/home/superdin/Desktop/NTHS/node_modules/express/lib/router/route.js:144:13)
      at Route.dispatch (/home/superdin/Desktop/NTHS/node_modules/express/lib/router/route.js:114:3)
      at Layer.handle [as handle_request] (/home/superdin/Desktop/NTHS/node_modules/express/lib/router/layer.js:95:5)
      at /home/superdin/Desktop/NTHS/node_modules/express/lib/router/index.js:284:15
      at Function.process_params (/home/superdin/Desktop/NTHS/node_modules/express/lib/router/index.js:346:12)
}
```

**Comment by dmgnr** [comment]
wait now it work?? ok fine im closing this

**Comment by dmgnr** [comment]
wait no, it work because i left it loading for like 10 minutes, and click the button again

**Comment by Faf4a** [comment]
I'm pretty sure that one of the Server Owners isn't cached, you can use `$cacheMembers[guildID?;returnCount?]` to fix that issue, if it's not the case then it'll leave this up to @Bumblebee-3.

**Comment by dmgnr** [comment]
Btw how do i do aoi eval programmatically?

**Comment by Bumblebee-3** [comment]
@5UP3R-D1N you need to cache all members like how @Faf4a mentioned

**Comment by Bumblebee-3** [comment]
Inactive, hence marking it as resolved...
